### PR TITLE
[PR] Adding custom events for page searched pages + depth 

### LINKED ISSUE #11: Custom Events + "User Journey" Deep Dive 👤 📈 🔍
# Story

As an engineer building a web-based software product, 
I would like to **log _custom_ events** per unique ***session*** to the `Analytics` backend
**So that** I can **_visualise_** the "***User Journey***" in _same_ interface as all other `Analytics` events/data (page views, etc.)

As noted in https://github.com/dwyl/learn-analytics/issues/11#issuecomment-2345486960 ⬇️ the stats collected by ("Plausible Community Edition") are "basic".
> Hence forth referred to as just "_Analytics_" because _nobody_ (outside of a _microscopic_ group of hackers) has heard of "Plausible" and "Community Edition" raises unnecessary _time-wasting questions_!
Obviously we will continue to give "Plausible Co" full credit and continue to [_sponsor_](https://github.com/sponsors/plausible) their efforts. 
But the _branding_ is important for internal and external (client) discussions and _everyone_ knows "Analytics". 

# Todo  

+ [x] Create a `custom-events.md` file in this repo where we will document all knowledge acquired. 📝 
+ [x] ***Transfer*** the initial ["Exploring Custom Events"](https://github.com/dwyl/learn-analytics/tree/e61fe333888141410ad1f6f9366ffd08ad962b97/plausible#4-exploring-custom-events-in-plausible) doc into the `new` file. 📋 
+ [x] Read the custom events API docs: https://plausible.io/docs/events-api to see what is possible in terms of _Advanced_ usage. Specifically can we submit an event with a _unique_ **`session_id`** to track a given "User" journey? 
+ [x] Please ***Comment*** below what is _possible_ in terms of events and _specifically_:
  + [x] What `Types` of data can be sent to the API
  + [x] What can be _displayed_ in the `Plausible Anlytics` UI without any customisation/modification. 
  + [x] Can we generate a `session_id` and submit it to the API with each event
  so that all pages for a given `User-Agent` are tied into a "Journey"?
  the `session_id` would be saved in `localStorage` and read before sending each event. 

If we end up having to build our own UI components, that's fine (and _expected_), 
we just want to see how far we can get with the built-in UI. 

# Bonus Level

+ [x] Refresh our understanding of Page Scroll Depth: https://github.com/dwyl/atm/issues/108
> **Note**: my understanding is that `Plausible` haven't implemented it yet. ⏳ 
+ [x] Write a basic script that calculates the page scroll depth.
+ [x] Log it to the custom events api TBD.

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #11 

This PR addresses the custom events for searched pages and also the depth scrolling issue detailed in the same issue.

I've documented my progress, but here's a basic rundown regardless:
- the funnel analysis is only made available for paying Cloud customers. They are planning on rolling it over to CE (Community Edition) in the future -> find more information in https://github.com/plausible/analytics/discussions/3099.
- both `search` and `depth` custom events, although some may find awkward to visualize in the dashboard, the metric can be quantified by applying filters (using the custom properties inside the each custom event definition) that are applied to the whole dashboard. This is documented in the `custom-events.mdx` README file.
- adds tests

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
@nelsonic this should be now reviewable.

**Comment by LuchoTurtle** [comment]
@nelsonic tagging again in case you didn't see this.

**Comment by nelsonic** [comment]
Thanks for reminder. Saw it on my phone and then lost the notification. 🤦‍♂️

**Comment by nelsonic** [comment]
Sorry for delay ... Going to take a look at this tonight after work-work. ⏳ 
Gotta focus on "Calculations" for the rest of the day. 🧑‍💻 🧮

**Comment by nelsonic** [comment]
In case you're wondering why this hasn't been merged yet, I'm just tidying a few things. 🧑‍💻 ⏳

**Review by nelsonic — APPROVED** [review]
Great work @LuchoTurtle thanks again. 📈 🎉 
Remember to ⭐ the repo you've poured so much effort into! 😉

**Pull request merged**
