### PR TITLE
[PR] Documenting self-hosting `Plausible CE`

### LINKED ISSUE #3: Deploy `Plausible Analytics` to a `VPS` 📈 📊 🚀 + Document it! 📝
We've been using (and gladly paying for) `Plausible Analytics` for the past couple of years: https://github.com/dwyl/technology-stack/issues/127
The plan was _always_ to experiment with self-hosting it so that we can more _features_ to analytics and have more _control_ over the `data` of the `people` using our App(s). 

With that in mind we need ...

# Todo

+ [x] Get: https://github.com/plausible/analytics running on `localhost` and document all the steps. 📝 
  e.g. `analytics/deploy-plausible-vps.md` 🆕 
+ [x] Use `Docker` (with `Ubuntu`) to run it on `localhost` so that it's easier to deploy on `VPS` 💻 
+ [x] We should be able to use `docker run` or  `mix start` in the `/analytics` directory and have it start up seamlessly 🚀 
+ [x] Create PR at this point. 🙏 
+ [x] Attempt to deploy to `fly.io` (which should be straightforward. 🤞); document the steps. 

> **Note**: the VPS we will be using is a `Droplet` on `DigitalOcean` 
but the instructions should be applicable to _any_ `VPS` provider including `AWS` etc.

If this is straightforward to deploy we will propose it for use by the `Client` who need an "[**On Prem**](https://en.wikipedia.org/wiki/On-premises_software)" analytics option;
i.e. their data is sensitive and don't want to send it to a 3<sup>rd</sup>Party. 

If this goes well, we will switch over the analytics of [dwyl.com](https://dwyl.com/) to analytics.dwyl.com 📈 
But our _goal_ is to use this as the _basis_ for building something a _lot_ more interesting! 😉

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #3 

This PR focuses on adding `Plausible CE` self-hosted on `localhost`, integrating it with a `Next.js` to exchange events that can later be displayed/have insights from in the self-hosted `Plausible` server instance.

All the steps are documented.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
Added documentation for `fly.io` and `DigitalOcean` (partial, given that I need the `hostname` to get it to work).

**Comment by nelsonic** [comment]
https://dash.cloudflare.com/a8700dad540bfd2b1c20a00a65795d56/dwyl.com/dns/records
image

IP address from: https://cloud.digitalocean.com/droplets/438832003
image

But I've just seen that this is hosted in the `FRA1` (`Frankfurt`) region ... 
whereas the DB https://cloud.digitalocean.com/databases/38253546-fe28-4a33-9a44-cb175b6f698f?i=933568 in `LON` (`London`) ... so we'll be re-deploying this to `Lon` or switching over the DB to `FRA` at some point. ⏳

**Comment by LuchoTurtle** [comment]
Thanks! Can't really log into the link but the image shows it's done, so cheers!

**Comment by LuchoTurtle** [comment]
@nelsonic this should be ready for review. 
When you merge this PR, a simple `HTML` page will also be published to `Github Pages` in this repository. It doesn't have the `Plausible` script yet because we're going to have you register (and, therefore, become `admin`) in [analytics.dwyl.com](https://analytics.dwyl.com/) so you can then add the site to monitor and get the script snippet.

After that, I'll create a micro-PR to add the script so you can see `Plausible` working.

**Review by nelsonic — APPROVED** [review]
Thanks @LuchoTurtle 👌 
As discussed, merging this now to unblock your work. 🧑‍💻 
I will review it more depth on the weekend. ⏳

**Pull request merged**
